services:
    organizer-user-service:
        build:
            context: ./
            target: dev
        container_name: organizer-user-service
        volumes:
            - .:/home/node/app
        restart: always
        env_file: .env
        networks:
            - organizer
        ports:
            - '3001:3001'
        command: npm start
        environment:
            - TYPEORM_URL=mongodb://root:${MONGO_ROOT_PASSWORD}@mongo-db:27017/Organizer-user?authSource=admin

    mongo-db:
        image: mongo
        container_name: mongo-db
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=&{DB_NAME}
        # Se você precisar do acesso do banco em outro app
        # ports:
        #     - '27017:27017'
        networks:
            - organizer

    # SE PRECISAR DE UM INTERFACE PARA GESTÃO DO BANCO DE DADOS
    # mongo-express:
    #     image: mongo-express
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    #         ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo-db:27017/
    #     networks:
    #         - organizer

networks:
    organizer:
        external: true
